import Head from 'next/head'
import styles from '../styles/Home.module.css'
// components 
import InputTodo from '../components/inputTodo';
import ListTodo from '../components/listTodo';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>PERN fontend app</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous"></link>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
      </Head>

      <InputTodo />

      <ListTodo />

      <footer className={styles.footer}>
        my foots: )
      </footer>
    </div>
  )
}
