import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>PERN</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1>PERN fontend app</h1>

      <footer className={styles.footer}>
        my foots :)
      </footer>
    </div>
  )
}
